toolbar:
  - styleselect | bold italic | undo redo
  - image | link
plugins:
  - image
  - link
alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table
